# Generated by Django 4.2.dev20221222061217 on 2023-02-22 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanda',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanda',
            name='complaintDetails',
            field=models.TextField(default='lodge your complaint here'),
        ),
    ]
