# Generated by Django 4.1.4 on 2023-04-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_tanda_date_created_alter_tanda_complaintdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanda',
            name='complaintDetails',
            field=models.TextField(default='lodge your complaints here'),
        ),
    ]
