# Generated by Django 4.2 on 2023-04-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_alter_tanda_complaintdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanda',
            name='complaintDetails',
            field=models.TextField(default='lodge your complaints here', max_length=80),
        ),
        migrations.AlterField(
            model_name='tanda',
            name='complaintType',
            field=models.CharField(choices=[('issue with staff', 'ISSUE WITH STAFF'), ('issue with food', 'ISSUE WITH FOOD'), ('both', 'BOTH')], default='issue with staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='tanda',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tanda',
            name='recommendation',
            field=models.TextField(blank=True, max_length=80),
        ),
    ]
