# Generated by Django 5.0.1 on 2024-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_tanda_complaintdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ImageField(height_field=20, upload_to='', width_field=20)),
            ],
        ),
    ]
