# Generated by Django 5.0.1 on 2024-01-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_galery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ImageField(upload_to='gallery/')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
    ]
