# Generated by Django 5.0.1 on 2024-01-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_alter_gallery_description_alter_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
