# Generated by Django 5.0.1 on 2024-01-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_alter_gallery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanda',
            name='complaintDetails',
            field=models.TextField(default='Write your complaints here', max_length=80),
        ),
    ]
